#!/bin/bash
set -e

sqlplus json/json@//localhost:1521/XEPDB1 <<-EOSQL

CREATE TABLE pages (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    type varchar2(255),
    -- Oracle Docs use clob in examples in version 12 and varchar2(23767) in version 18 examples
    -- Not sure why exactly 23767 bytes used, doesnt work in default config of database attributes varchar2(4000),
    attributes varchar2(4000),
    CONSTRAINT "PAGES_ID_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "ENSURE_JSON_ATTRIBUTE" CHECK (attributes IS JSON)
);

INSERT INTO pages (type, attributes) VALUES ( 'single', '{"singleAttribute":{"type":"String","value":"test"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"firstHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"firstHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"firstHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"firstHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"firstHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"secondHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"secondHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"secondHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"secondHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'ten', '{"tenAttribute":{"type":"String","value":"secondHalf"}}' );
INSERT INTO pages (type, attributes) VALUES ( 'rand', '{}' );
INSERT INTO pages (type, attributes) VALUES ( 'rand', '{}' );
INSERT INTO pages (type, attributes) VALUES ( 'rand', '{}' );

exit;
EOSQL