#!/bin/bash
## Maybe change testdata creation to a csv import to ease compatibility and maintainability...

set -e

sqlplus eav/eav@//localhost:1521/XEPDB1 <<-EOSQL

CREATE TABLE entities (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	typename varchar2(255),
  CONSTRAINT "ENTITIES_ID_PK" PRIMARY KEY ("ID")
);


CREATE TABLE attributes (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	datatype varchar2(255),
	name varchar2(255),
	CONSTRAINT "ATTRIBUTES_ID_PK" PRIMARY KEY ("ID")
);

CREATE TABLE eav_values (
	ent_id NUMBER,
	att_id Number,
	value varchar2(255),
	CONSTRAINT "EAV_VALUES_PK_D" PRIMARY KEY (ent_id, att_id)
);

-- Just Oracle things
INSERT  INTO entities (typename) VALUES ('single');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('ten');
INSERT  INTO entities (typename) VALUES('rand');
INSERT  INTO entities (typename) VALUES('rand');
INSERT  INTO entities (typename) VALUES('rand');
INSERT  INTO entities (typename) VALUES('complex');

INSERT INTO attributes (datatype, name ) VALUES ( 'String', 'singleAttribute' );
INSERT INTO attributes (datatype, name ) VALUES ( 'String', 'tenAttribute' );
INSERT INTO attributes (datatype, name ) VALUES ( 'String', 'moreAttribute1' );
INSERT INTO attributes (datatype, name ) VALUES ( 'String', 'moreAttribute2' );
INSERT INTO attributes (datatype, name ) VALUES ( 'String', 'moreAttribute3' );
INSERT INTO attributes (datatype, name ) VALUES ( 'String', 'moreAttribute4' );

INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 1,1, 'test' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 2,2, 'firstHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 3,2, 'firstHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 4,2, 'firstHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 5,2, 'firstHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 6,2, 'firstHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 7,2, 'secondHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 8,2, 'secondHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 9,2, 'secondHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 10,2, 'secondHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 11,2, 'secondHalf' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 15,3, '1' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 15,4, '2' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 15,5, '3' );
INSERT  INTO eav_values (ent_id, att_id, value) VALUES ( 15,6, '4' );
exit;
EOSQL